[project]
name = "scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachetools>=7.0.5",
    "confluent-kafka>=2.13.0",
    "networkx>=3.0",
    "paramiko>=3.3.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "requests>=2.31.0",
    "shared",
    "voluptuous>=0.16.0",
]

[tool.uv.sources]
shared = { path = "../Shared", editable = true }

[project.scripts]
torri-merger = "torri.cmd.merger:main"
torri-scheduler = "torri.cmd.scheduler:main"

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
