[program:status-api]
command=/opt/venv/bin/uvicorn status_api.server:app --host 0.0.0.0 --port 8000
directory=/app/Torri/src
autostart=true
autorestart=true
stdout_logfile=/app/logs/status_api.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/app/logs/status_api.log
stderr_logfile_maxbytes=0
