# Pipeline Definitions
# Simple test pipelines for demo/development

pipelines:
  # Basic verification pipeline
  - pipeline:
      name: check
      manager: independent
      start-message : "Starting check jobs"
      require:
        open: true
        current-patchset: true
        approval:
          - code-review: 2
          - verified: 1
      reject:
        approval:
          - integrated: [-2, -1]

      trigger:
        gerrit:
          - event: patchset-created
      success:
        gerrit:
          - Verified: 1
      failure:
        gerrit:
          - Verified: -1

  - pipeline:
      name: gate
      start-message : "Starting gate jobs"
      failure-message: 
      manager: dependent
      require:
        open: true
        current-patchset: true
        approval:
          - code-review: 2
          - verified: 1

      trigger:
        gerrit:
          - event: comment-added
      success:
        gerrit:
          - Gatekeeper: 1
      failure:
        gerrit:
          - Gatekeeper: -1  
