"""
Unified ref pipeline manager for all pipelines.

Coordinates:
- Synthetic ref generation from Merger service
- Ref sharing across pipelines (Check, Gate, Report)
- Dependency-aware scheduling
- Pipeline state tracking
"""

import uuid
from typing import Dict, List, Optional, Tuple
from datetime import datetime
from shared.logger_setup import get_logger


class RefPipelineState:
    """Tracks state of a change across all pipelines."""
    
    def __init__(self, change_id: str):
        self.change_id = change_id
        self.synthetic_ref = None  # Generated by Merger
        
        # Pipeline states: NOT_STARTED, PROCESSING, SUCCESS, FAILED, SKIPPED
        self.check_pipeline_state = "NOT_STARTED"
        self.gate_pipeline_state = "NOT_STARTED"
        self.report_pipeline_state = "NOT_STARTED"
        
        # Timestamps
        self.enqueued_time = datetime.utcnow().isoformat()
        self.check_start_time = None
        self.gate_start_time = None
        self.report_start_time = None
        
        # Results
        self.check_result = None
        self.gate_result = None
        self.report_result = None
        
        # Dependencies
        self.depends_on = []  # List of change_ids this depends on
        self.blocked_by = []  # Which changes are blocking this
    
    def to_dict(self):
        """Serialize to dict for Redis storage."""
        return {
            'change_id': self.change_id,
            'synthetic_ref': self.synthetic_ref,
            'check_state': self.check_pipeline_state,
            'gate_state': self.gate_pipeline_state,
            'report_state': self.report_pipeline_state,
            'enqueued_time': self.enqueued_time,
            'check_start_time': self.check_start_time,
            'gate_start_time': self.gate_start_time,
            'report_start_time': self.report_start_time,
            'check_result': self.check_result,
            'gate_result': self.gate_result,
            'report_result': self.report_result,
            'depends_on': self.depends_on,
            'blocked_by': self.blocked_by,
        }


class UnifiedRefPipelineManager:
    """
    Manages synthetic refs and state across all pipelines.
    
    Workflow:
    1. Change enqueued → stored in Redis with state NOT_STARTED
    2. Ref requested → Merger generates synthetic ref, stored
    3. Check pipeline processes → uses synthetic ref, updates state
    4. Gate pipeline processes → uses synthetic ref, updates state
    5. Gate submits → calls Gerrit REST API
    6. Report pipeline processes → records final state
    """
    
    def __init__(self, redis_client, merger_coordinator):
        self.logger = get_logger("torri.scheduler.ref_pipeline_manager")
        self.redis = redis_client
        self.merger = merger_coordinator
    
    def enqueue_change(
        self,
        change_id: str,
        project_name: str,
        branch: str,
        depends_on: List[str] = None
    ) -> RefPipelineState:
        """
        Register a change for processing across all pipelines.
        
        Returns initial RefPipelineState with dependency info.
        """
        try:
            state = RefPipelineState(change_id)
            state.depends_on = depends_on or []
            
            # Check for chains: who is blocked by this change
            blocked = self._find_blocked_changes(change_id)
            state.blocked_by = blocked
            
            # Store in Redis
            self._store_state(change_id, state)
            
            self.logger.info(
                "Enqueued change %s project=%s branch=%s depends_on=%s",
                change_id, project_name, branch, depends_on
            )
            
            return state
        
        except Exception as e:
            self.logger.error("Error enqueueing change: %s", e)
            raise
    
    def request_synthetic_ref(
        self,
        change_id: str,
        project_name: str,
        base_branch: str,
        patchset_refs: List[str],
        strategy: str = "merge"
    ) -> Tuple[bool, Optional[str]]:
        """
        Request Merger to generate synthetic ref for this change.
        
        This runs ONCE per change, result shared across all pipelines.
        """
        try:
            state = self._get_state(change_id)
            
            # Already have ref?
            if state.synthetic_ref:
                self.logger.debug("Using cached synthetic ref for %s: %s", change_id, state.synthetic_ref)
                return True, state.synthetic_ref
            
            # Request from Merger
            job_id = f"change-{change_id}-{uuid.uuid4().hex[:8]}"
            
            self.logger.info(
                "Requesting synthetic ref for change=%s job_id=%s refs=%s",
                change_id, job_id, patchset_refs
            )
            
            success, result = self.merger.request_synthetic_ref(
                job_id=job_id,
                target_repo=f"gerrit:{project_name}.git",
                base_branch=base_branch,
                patchset_refs=patchset_refs,
                strategy=strategy
            )
            
            if success:
                synthetic_ref = result
                # Store ref in state
                state.synthetic_ref = synthetic_ref
                self._store_state(change_id, state)
                
                self.logger.info(
                    "Got synthetic ref for change=%s ref=%s",
                    change_id, synthetic_ref
                )
                return True, synthetic_ref
            else:
                error_msg = result
                self.logger.error(
                    "Failed to get synthetic ref for change=%s: %s",
                    change_id, error_msg
                )
                return False, error_msg
        
        except Exception as e:
            self.logger.error("Error requesting synthetic ref: %s", e)
            return False, str(e)
    
    def can_pipeline_process(self, change_id: str, pipeline_name: str) -> Tuple[bool, Optional[str]]:
        """
        Check if a pipeline can process this change.
        
        Rules:
        - Check pipeline: Can always start (independent)
        - Gate pipeline: Only if Check succeeded AND dependencies merged/ready
        - Report pipeline: Only if Gate completed
        """
        try:
            state = self._get_state(change_id)
            
            if pipeline_name == "check":
                # Check can always run, but needs synthetic ref
                if not state.synthetic_ref:
                    return False, "Synthetic ref not ready"
                return True, None
            
            elif pipeline_name == "gate":
                # Gate needs Check to pass
                if state.check_pipeline_state != "SUCCESS":
                    return False, f"Check not complete (state={state.check_pipeline_state})"
                
                # Gate needs dependencies to be merged/ready
                for dep_id in state.depends_on:
                    dep_state = self._get_state(dep_id)
                    if dep_state and dep_state.gate_pipeline_state != "SUCCESS":
                        return False, f"Dependency {dep_id} not merged (state={dep_state.gate_pipeline_state})"
                
                return True, None
            
            elif pipeline_name == "report":
                # Report runs after Gate
                if state.gate_pipeline_state != "SUCCESS":
                    return False, f"Gate not complete (state={state.gate_pipeline_state})"
                return True, None
            
            else:
                return False, f"Unknown pipeline: {pipeline_name}"
        
        except Exception as e:
            self.logger.error("Error checking pipeline readiness: %s", e)
            return False, str(e)
    
    def update_pipeline_state(
        self,
        change_id: str,
        pipeline_name: str,
        new_state: str,
        result: Dict = None
    ):
        """
        Update pipeline state for a change.
        
        States: NOT_STARTED, PROCESSING, SUCCESS, FAILED, SKIPPED
        """
        try:
            state = self._get_state(change_id)
            
            if pipeline_name == "check":
                state.check_pipeline_state = new_state
                state.check_result = result
                if new_state == "PROCESSING":
                    state.check_start_time = datetime.utcnow().isoformat()
            
            elif pipeline_name == "gate":
                state.gate_pipeline_state = new_state
                state.gate_result = result
                if new_state == "PROCESSING":
                    state.gate_start_time = datetime.utcnow().isoformat()
            
            elif pipeline_name == "report":
                state.report_pipeline_state = new_state
                state.report_result = result
                if new_state == "PROCESSING":
                    state.report_start_time = datetime.utcnow().isoformat()
            
            self._store_state(change_id, state)
            
            self.logger.info(
                "Updated state: change=%s pipeline=%s state=%s",
                change_id, pipeline_name, new_state
            )
        
        except Exception as e:
            self.logger.error("Error updating pipeline state: %s", e)
    
    def get_dependent_queue(self, change_id: str) -> List[str]:
        """Get list of changes waiting on this one."""
        try:
            state = self._get_state(change_id)
            return state.blocked_by if state else []
        except Exception as e:
            self.logger.error("Error getting dependent queue: %s", e)
            return []
    
    def is_dependent_processing(self, change_id: str) -> bool:
        """Check if any dependent is currently in a pipeline."""
        try:
            for dep_id in self.get_dependent_queue(change_id):
                dep_state = self._get_state(dep_id)
                if dep_state:
                    # Check if any pipeline is processing
                    if dep_state.check_pipeline_state == "PROCESSING":
                        return True
                    if dep_state.gate_pipeline_state == "PROCESSING":
                        return True
                    if dep_state.report_pipeline_state == "PROCESSING":
                        return True
            return False
        except Exception as e:
            self.logger.error("Error checking dependent processing: %s", e)
            return False
    
    # ========== Helpers ==========
    
    def _store_state(self, change_id: str, state: RefPipelineState):
        """Store state in Redis."""
        key = f"torri:change:{change_id}:pipeline_state"
        self.redis.set_state(key, state.to_dict())
    
    def _get_state(self, change_id: str) -> Optional[RefPipelineState]:
        """Retrieve state from Redis."""
        key = f"torri:change:{change_id}:pipeline_state"
        data = self.redis.get_state(key)
        
        if not data:
            return None
        
        state = RefPipelineState(change_id)
        state.synthetic_ref = data.get('synthetic_ref')
        state.check_pipeline_state = data.get('check_state', 'NOT_STARTED')
        state.gate_pipeline_state = data.get('gate_state', 'NOT_STARTED')
        state.report_pipeline_state = data.get('report_state', 'NOT_STARTED')
        state.enqueued_time = data.get('enqueued_time')
        state.check_start_time = data.get('check_start_time')
        state.gate_start_time = data.get('gate_start_time')
        state.report_start_time = data.get('report_start_time')
        state.check_result = data.get('check_result')
        state.gate_result = data.get('gate_result')
        state.report_result = data.get('report_result')
        state.depends_on = data.get('depends_on', [])
        state.blocked_by = data.get('blocked_by', [])
        
        return state
    
    def _find_blocked_changes(self, change_id: str) -> List[str]:
        """Find all changes that depend on this one."""
        # This would scan Redis for changes with this in their depends_on list
        # For now, return empty - would be populated as changes are enqueued
        return []
