
services:
  gerrit:
    pull_policy: build
    build:
      dockerfile_inline: | 
        FROM gerritcodereview/gerrit:${GERRIT_TAG}
        COPY --link --chown=1000:1000 --from=gerrit_config /etc/ /var/gerrit/etc/
        COPY --link --chown=1000:1000 --from=gerrit_config  --chmod=600 /ssh/ /var/gerrit/.ssh/
        COPY --link --chown=1000:1000 --from=gerrit_config /plugins/events-kafka.jar /var/gerrit/plugins/
        COPY --link --chown=1000:1000 --from=gerrit_config /plugins/events-broker.jar /var/gerrit/lib/
      additional_contexts:
        gerrit_config : files/gerrit/
    networks:
      - torii

  gerrit-config:
    pull_policy : build
    build : 
      dockerfile_inline: |
        FROM mikefarah/yq:${YQ_TAG:?}
        USER root
        RUN apk add --no-cache openssh-client bash curl findutils git docker-cli
        RUN rm -rf /root/.ssh && mkdir --mode=700 /root/.ssh
        COPY --link --chmod=600 --from=ssh_files / /root/.ssh/
        COPY --link --from=layout_file / /root/
      additional_contexts:
        ssh_files : files/ssh/
        layout_file : files/torri/
    container_name: gerrit-config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - torii
  kafka-config:
    pull_policy: build
    build:
      dockerfile_inline: |
        FROM alpine:${ALPINE_TAG}
        RUN apk add --no-cache docker-cli bash
    container_name: kafka-config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:alpine
    container_name: nginx
    # depends_on:
    #   gerrit:
    #     condition: service_healthy
    #   jenkins:
    #     condition: service_healthy
#     extends:
#       file: ./jenkins.yaml
#       service: jenkins
#     depends_on:
#       gerrit:
#         condition: service_healthy

# networks:
#   torii:
#     driver: bridge

# volumes:
#   gerrit_data:
#   jenkins_home:
    
