
services:
  gerrit:
    pull_policy: build
    build:
      dockerfile_inline: | 
        FROM gerritcodereview/gerrit:${GERRIT_VERSION}
        COPY --from=gerrit_config /gerrit.config /var/gerrit/etc/
      additional_contexts:
        gerrit_config : files/gerrit/
    networks:
      - torri

  gerrit-config:
    pull_policy : build
    build : 
      dockerfile_inline: |
        FROM alpine:latest 
        COPY --from=ssh_files / /root/.ssh/
        COPY --from=layout_file / /tmp/layout/
        #ensure a propper permissions for the ssh files and configs
        RUN chmod 600 /root/.ssh/*
        RUN apk --no-cache add bash curl yq openssh-client git
      additional_contexts:
        ssh_files : files/ssh/
        layout_file : files/torri/
    container_name: gerrit-config
    restart: "no"
    depends_on:
      gerrit:
        condition: service_healthy
      nginx:
        condition: service_healthy

    networks:
      - torri

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes: 
      - ./files/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - "8087:8087"
    healthcheck:
      test : ["CMD-SHELL" , "curl -f http://localhost:8087/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 70s

    networks:
      - torri
    depends_on:
      gerrit:
        condition: service_healthy
    
networks:
  torri:
    name: torri

    # depends_on:
    #   gerrit:
    #     condition: service_healthy
    #   jenkins:
    #     condition: service_healthy
#     extends:
#       file: ./jenkins.yaml
#       service: jenkins
#     depends_on:
#       gerrit:
#         condition: service_healthy

# networks:
#   torii:
#     driver: bridge

# volumes:
#   gerrit_data:
#   jenkins_home:
    
