name: torri-compose
include:
  - env_file: ./default.env
    path:
      - ./redis.yaml
      - ./gerrit.yaml
      - ./nginx.yaml
      - ./kafka.yaml
      - ./server.yaml
      - ./web.yaml

networks:
  torii:
    name: torii
