services:
  gerrit:
    image: gerritcodereview/gerrit:${GERRIT_VERSION}
    container_name: gerrit
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "29418:29418"
    enviroments:
      CANONICAL_WEB_URL = http://gerrit:8080/g
      HTTPD_LISTEN_URL = proxy-http://*:8080/g
    volumes:
      - gerrit_etc:/var/gerrit/etc
      - gerrit_git:/var/gerrit/git
      - gerrit_index:/var/gerrit/index
      - gerrit_cache:/var/gerrit/cache
      - gerrit_plugins:/var/gerrit/plugins
      - ./files/gerrit:/bootstrap:ro
    entrypoint: ["/bin/sh" ,"-c"]
    command: 
         - |
           set -e  
           [ -f /var/gerrit/etc/gerrit.config ] || cp /bootstrap/gerrit.config /var/gerrit/etc/
           exec /entrypoint.sh 

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/config/server/info || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 24
      start_period: 60s
    networks:
      - torii
  gerrit-config:
    image: curl

volumes:
  gerrit_etc:
  gerrit_git:
  gerrit_index:
  gerrit_cache:
  gerrit_plugins:

networks:
  torii:
    name: torii
