version: "3.9"

services:
  gerrit:
    image: gerritcodereview/gerrit:latest
    container_name: gerrit
    restart: unless-stopped
    depends_on:
      - ldap
      - postgres
    ports:
      - "8081:8080"
      - "29418:29418"
    volumes:
      - gerrit_data:/var/gerrit
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 24
      start_period: 60s
    networks:
      - torii
  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - /external/gerrit/ldap/var:/var/lib/ldap
      - /external/gerrit/ldap/etc:/etc/ldap/slapd.d

  ldap-admin:
    image: osixia/phpldapadmin
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
networks:
  torii:
    name: torii

volumes:
  gerrit_data:
