services:
  gerrit:
    image: gerritcodereview/gerrit:${GERRIT_VERSION}
    container_name: gerrit
    restart: unless-stopped
    volumes:
      - gerrit_etc:/var/gerrit/etc
      - gerrit_git:/var/gerrit/git
      - gerrit_index:/var/gerrit/index
      - gerrit_cache:/var/gerrit/cache
      - gerrit_plugins:/var/gerrit/plugins
      - ./files/gerrit:/bootstrap:ro
    entrypoint: ["/bin/sh" ,"-c"]
    command: 
         - |
           set -e  pipefail
           [ -f /var/gerrit/etc/gerrit.config ] || cp /bootstrap/gerrit.config /var/gerrit/etc/

           exec /entrypoint.sh 

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/login || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 24
      start_period: 60s
    networks:
      - torii
  gerrit-config:
    extends: 
      file: build.yaml
      service: gerrit-config
      entrypoint: 
        - bash 
        - c
      command: 
      - | 
        set -uoe pipefail -x
        # create the account with curl 
        curl -X GET http://localhost:8087/g/ -H "X-Bootstrap-Token: secret"
        curl -X POST http://localhost:8087/g/a/accounts/self/sshkeys \
          -H "X-Bootstrap-Token: secret" \
          -H "Content-Type: text/plain" \
          --data-binary @/root/.ssh/Torri_ed25519.pub \
        # create the projects with yg 
         while IFS="|" read -r name branches; do
            project_branches["$${name}"]="$${branches}"
         done < <(yq -r '.projects[] | .name + "|" + (.branches | join(" "))' /tmp/layout/projects.yaml)
         # loop through the projects and branches and create them 
         for proj in "$${!project_branches[@]}"; do
            ssh gerrit gerrit create-project "$${proj}" --empty-commit || echo "  -> Exists"
            branches_string="$${project_branches[$${proj}]}"
            current_branches=($${branches_string})
            for branch in "$${current_branches[@]}"; do
                if [[ -n "$${branch}" ]]; then
                    ssh gerrit gerrit create-branch "$${proj}" "$${branch}" master || echo "  -> Branch exists"
                fi
            done
        done
        

volumes:
  gerrit_etc:
  gerrit_git:
  gerrit_index:
  gerrit_cache:
  gerrit_plugins:

networks:
  torii:
    name: torii
