services:
  gerrit:
    image: gerritcodereview/gerrit:${GERRIT_VERSION}
    container_name: gerrit
    restart: unless-stopped
    volumes:
      - gerrit_etc:/var/gerrit/etc
      - gerrit_git:/var/gerrit/git
      - gerrit_index:/var/gerrit/index
      - gerrit_cache:/var/gerrit/cache
      - gerrit_plugins:/var/gerrit/plugins
      - ./files/gerrit:/bootstrap:ro
    entrypoint: ["/bin/sh" ,"-c"]
    command: 
         - |
           set -e  
           [ -f /var/gerrit/etc/gerrit.config ] || cp /bootstrap/gerrit.config /var/gerrit/etc/

           exec /entrypoint.sh 

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/login || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 24
      start_period: 60s
    networks:
      - torii
  gerrit-config:
    pull-policy : build
    build : 
      docker-inline: |
        FROM curlimages:curl:${CURL_VERSION}
        COPY --from=ssh_files / /root/.ssh/
        

        FROM 
        COPY --from=layout_file /layout.yaml /root/
      additional_context:
        ssh_files : .files/ssh/
        layout_file : .files/torri/


volumes:
  gerrit_etc:
  gerrit_git:
  gerrit_index:
  gerrit_cache:
  gerrit_plugins:

networks:
  torii:
    name: torii
