services:
  scheduler:
    pull_policy: build
    build:
      context: ../
      dockerfile: compose/Dockerfile
      target: scheduler
    container_name: torii_scheduler
    # volumes:
      # - ./logs/scheduler:/app/Torri/src/torri/ephemeral/logs
    networks:
      - torii
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_SERVER: kafka:9092

  merger:
    pull_policy: build
    build:
      context: ../
      dockerfile: compose/Dockerfile
      target: merger
    container_name: merger_service
    volumes:
      - ./logs/merger/:/tmp/ephemeral/logs/
    networks:
      - torii
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_SERVER: kafka:9092



