services:
  scheduler:
    pull_policy: build
    build:
      context: ../
      dockerfile: compose/Dockerfile
      target: scheduler
    container_name: torii_scheduler
    volumes:
      - ./logs/scheduler:/app/ephemeral/logs
    networks:
      - torii
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-config:
        condition: service_completed_successfully
    environment:
      KAFKA_SERVER: kafka:9092
      REDIS_URL: redis://redis:6379/0
      LOG_DIR: /app
    expose:
      - "8000"
    ports:
      - "8000:8000"

  merger:
    pull_policy: build
    build:
      context: ../
      dockerfile: compose/Dockerfile
      target: merger
    container_name: merger_service
    volumes:
      - ./logs/merger/:/tmp/ephemeral/logs/
    networks:
      - torii
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-config:
        condition: service_completed_successfully
    environment:
      KAFKA_SERVER: kafka:9092
      REDIS_URL: redis://redis:6379/0



